### ISSUE TITLE
There is no datasets package in the same directory, this seems to be a bug

### ISSUE THREAD

**Issue by BrightMoonStar** [UT-Austin-RPL/Lotus#1]
There is no datasets package in the same directory, this seems to be a bug

https://github.com/UT-Austin-RPL/Lotus/blob/e1027fcc60a24acb18b8d5ecf0f19b268eda86dc/lotus/skill_learning/dinov2/dinov2/data/loaders.py#L14

**Comment by wkwan7** [comment]
Hi! Thank you for pointing this out. We have fixed this.
