### ISSUE TITLE
How to Visualize During Training

### ISSUE THREAD

**Issue by 74284853** [UT-Austin-RPL/Lotus#2]
When I train, I only have terminal information but cannot visualize the simulation environment. How should I set it to be visible？
![image](https://github.com/UT-Austin-RPL/Lotus/assets/75053635/1e0aa837-eaf4-4de7-80fc-af9570e2ba53)
![Uploading image.png…]()

**Comment by wkwan7** [comment]
Hi @74284853. The training process is an imitation (supervised) learning process. We do not need to interact with the simulator during training.  However, you can use [eval.py](https://github.com/UT-Austin-RPL/Lotus/blob/master/lotus/lifelong/evaluate.py) to visualize the rollout trajectory (save videos).
