### ISSUE TITLE
Can't use "lifelong=multitask_skill" 

### ISSUE THREAD

**Issue by Valarzz** [UT-Austin-RPL/Lotus#3]
Hi, when I'm running this command:
```
export CUDA_VISIBLE_DEVICES=GPU_ID && \
export MUJOCO_EGL_DEVICE_ID=GPU_ID && \
python lotus/lifelong/main_old.py seed=SEED \
                               benchmark_name=BENCHMARK \
                               policy=bc_transformer_policy \
                               lifelong=multitask_skill \
                               skill_learning.exp_name={SKILL_EXP_NAME} \
                               exp={EXP_NAME} \
                               goal_modality=BUDS
```
It raises an error saying that there's no `multitask_skill` algorithm.
I check with the registered algorithms [REGISTERED_ALGOS](https://github.com/UT-Austin-RPL/Lotus/blob/38cb993b473d15df1b2712c0787ad058cdd4b030/lotus/lifelong/algos/base.py#L30), and it prints: 
```
{'sequential', 'multitask', 'er', 'agem', 'ewc', 'packnet', 'singletask', 'subskill', 'metacontroller'}
```
I wonder if I missed any steps so that I didn't have the multitask_skill algorithm.

**Comment by wkwan7** [comment]
Hi @Valarzz, there's a typo in this script. We need to use "main.py" for hierarchical skill-based policy training. I have updated README. Thanks!
