### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by BrightMoonStar** [UT-Austin-RPL/Lotus#5]
Hi~
Your work LOTUS is very attractive to me！Could you share which hardware setup you used for training and roughly how long one training run took on that setup?In particular, does the project support parallel computing on multiple GPUs?
Thanks a lot !

**Comment by wkwan7** [comment]
Hi! We did all the experiments on NVIDIA RTX A5000.  For LIBERO-OBJECT and LIBERO-GOAL it should take ~4-5 hours. For LIBERO-50 it should take 1-2 days. The current codebase does not support parallel training, but you can use different GPU for rendering and training, for example:`export CUDA_VISIBLE_DEVICES=0,1 && export MUJOCO_EGL_DEVICE_ID=1 && python xxx`
